name: Package

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Update version
        uses: pocket-apps/action-update-version@v1
        with:
          files: 'VERSION'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}