name: Package

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Echo VERSION
        run: echo "${{ steps.version.outputs.content }}"
