name: Package

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Echo VERSION
        run: echo "${{ steps.version.outputs.content }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.version.outputs.content }}

      - name: Echo VERSION
        run: echo "${{ steps.semvers.outputs.patch }}"

      - name: Set Git Identity
        run: |
          git config user.email "bump-version@yeenbot.io"
          git config user.name "Version Bumper"

      - name: Bump version in VERSION file
        id: bump
        run: |
          echo "${{ steps.semvers.outputs.patch }}" > VERSION 
          git commit -m "Bump version to ${{ steps.semvers.outputs.patch }}" VERSION 

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: ${{ github.ref }}