name: Package

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Echo VERSION
        run: echo "${{ steps.version.outputs.content }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.version.outputs.content }}

      - name: Echo VERSION
        run: echo "${{ steps.semvers.outputs.patch }}"

      - name: Set Git Identity
        run: |
          git config user.email "bump-version@yeenbot.io"
          git config user.name "Version Bumper"

      - name: Bump version in VERSION file
        id: bump
        run: |
          echo "${{ steps.semvers.outputs.patch }}" > VERSION 

      - name: Update resources
        uses: test-room-7/action-update-file@v2
        with:
          file-path: VERSION
          commit-msg: Bump version to ${{ steps.semvers.outputs.patch }}
          github-token: ${{ secrets.GITHUB_TOKEN }}