name: Package

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Echo VERSION
        run: echo "${{ steps.version.outputs.content }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.version.outputs.content }}

      - name: Echo VERSION
        run: echo "${{ steps.semvers.outputs.patch }}"

      - name: Set new version
        uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: VERSION
          content: '${{ steps.semvers.outputs.patch }}'
          commit_message: 'Bump version to ${{ steps.semvers.outputs.patch }}'