name: Package

on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  issue-from-todos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create issues from TODOs
        uses: alstr/todo-to-issue-action@v5.1.11
        with:
          AUTO_ASSIGN: 'true'
          PROJECT: organization/yeencloud/Backlog
          PROJECTS_SECRET: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INSERT_ISSUE_URLS: 'true'
          CLOSE_ISSUES: 'true'